# Generated by Django 6.0 on 2026-08-16 13:09

from django.db import migrations, models





class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DexPassSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(default='DexPass', help_text='The name of the dexpass')),
                ('enabled', models.BooleanField(default=True, help_text='If the ball is enabled or not')),
            ],
            options={
                'verbose_name': 'DexPass Setting',
                'verbose_name_plural': 'DexPass Settings',
            },
        ),
    ]
