# Generated by Django 6.0 on 2026-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0002_setting_slob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(blank=True, default='bal', help_text='The name of the dexpass', null=True)),
                ('level', models.IntegerField(help_text='Level for this reward')),
                ('premium_reward', models.CharField(default=True, help_text='Premium reward. Hides it if unselected')),
            ],
            options={
                'verbose_name': 'DexPass Reward',
                'verbose_name_plural': 'DexPass Rewards',
            },
        ),
        migrations.AddField(
            model_name='dexpasssettings',
            name='premium_price',
            field=models.BooleanField(default=True, help_text='The cost to unlock the premium battlepass | enable currency. Disables *specifically* at 1298'),
        ),
        migrations.AlterField(
            model_name='dexpasssettings',
            name='enabled',
            field=models.BooleanField(default=True, help_text='If the pass is enabled or not'),
        ),
    ]
