# Generated by Django 6.0 on 2026-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0003_passrewards_dexpasssettings_premium_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passrewards',
            name='premium_reward',
            field=models.CharField(blank=True, help_text='Premium reward. Hides it if unselected', null=True),
        ),
    ]
