# Generated by Django 6.0 on 2026-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0004_alter_passrewards_premium_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexpasssettings',
            name='xp_to_complete',
            field=models.IntegerField(default=50000, help_text='The amount of XP required to beat the DexPass'),
        ),
    ]
