# Generated by Django 6.0 on 2026-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0005_dexpasssettings_xp_to_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='DexPassPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, help_text='Player xp')),
                ('discord_id', models.BigIntegerField(default=0, help_text='The players discord ID')),
            ],
            options={
                'verbose_name': 'DexPass Player',
                'verbose_name_plural': 'DexPass Players',
            },
        ),
    ]
