# Generated by Django 6.0 on 2026-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0006_dexpassplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexpasssettings',
            name='premium_name',
            field=models.CharField(blank=True, default='Premium', help_text='The premium thingy that gets appended to the name. Leave blank to disable premium. eg; DexPass Premium, Pro, Ultimate, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='dexpasssettings',
            name='premium_price',
            field=models.BooleanField(default=True, help_text='The cost to unlock the premium battlepass | enable currency.'),
        ),
    ]
