# Generated by Django 6.0 on 2026-08-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0007_dexpasssettings_premium_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexpassplayer',
            name='has_premium',
            field=models.BooleanField(default=False, help_text='Check for premium access.'),
        ),
        migrations.AlterField(
            model_name='dexpassplayer',
            name='discord_id',
            field=models.BigIntegerField(default=0, help_text='The players discord ID', unique=True),
        ),
    ]
