# Generated by Django 6.0 on 2026-08-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0008_dexpassplayer_has_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dexpasssettings',
            name='premium_price',
            field=models.IntegerField(default=True, help_text='The cost to unlock the premium battlepass | enable currency.'),
        ),
    ]
