# Generated by Django 6.0 on 2026-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0009_alter_dexpasssettings_premium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexpasssettings',
            name='season',
            field=models.IntegerField(default=1, help_text='Current DexPass Season'),
        ),
    ]
