# Generated by Django 6.0 on 2026-08-18 22:06

import dexpass.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dexpass', '0010_dexpasssettings_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
            bases=(dexpass.models.DexPassReward, models.Model),
        ),
        migrations.CreateModel(
            name='PassRewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.BooleanField(default=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('pass_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dexpass.passrewards')),
            ],
        ),
    ]
