# Generated by Django 6.0 on 2026-08-18 22:38

import dexpass.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0019_guildconfig_tips_enabled'),
        ('dexpass', '0011_currencyreward_passrewarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.special')),
            ],
            bases=(dexpass.models.DexPassReward, models.Model),
        ),
    ]
