# Generated by Django 6.0 on 2026-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0012_ballreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexpassplayer',
            name='level',
            field=models.IntegerField(default=0, help_text='Player level'),
        ),
        migrations.AddField(
            model_name='dexpasssettings',
            name='xp_per_catch',
            field=models.FloatField(default=0, help_text='Amount of xp you want the user to get upon catching. Leave at 0 to disable'),
        ),
    ]
