# Generated by Django 6.0 on 2026-09-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexpass', '0013_dexpassplayer_level_dexpasssettings_xp_per_catch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passrewards',
            options={'ordering': ['season', 'level'], 'verbose_name': 'DexPass Reward', 'verbose_name_plural': 'DexPass Rewards'},
        ),
        migrations.AddField(
            model_name='dexpassplayer',
            name='total_levels',
            field=models.IntegerField(default=0, help_text='Player levels that wont get reset with a new season'),
        ),
        migrations.AddField(
            model_name='dexpassplayer',
            name='total_xp',
            field=models.IntegerField(default=0, help_text='Player xp that wont get reset with a new season'),
        ),
        migrations.AddField(
            model_name='passrewards',
            name='season',
            field=models.IntegerField(default=0, help_text="The reward's season"),
        ),
        migrations.AddConstraint(
            model_name='passrewards',
            constraint=models.UniqueConstraint(fields=('season', 'level'), name='unique_dexpass_season_level'),
        ),
    ]
