# Generated by Django 6.0 on 2026-10-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0019_guildconfig_tips_enabled'),
        ('dexpass', '0014_alter_passrewards_options_dexpassplayer_total_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballreward',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_models.special'),
        ),
    ]
